import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"; // next-themes For
import SideBar from "@/components/SideBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Side Bar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SideBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
/************************
 * Notes
 * suppressHydrationWarning
 * it's important to use with next-them to make react understand and not render the server components
 * next-theme mode
 * light | dark | system
 *
 ************************/
